import { createHash } from 'node:crypto';
import { existsSync } from 'node:fs';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { cwd, env, stderr, stdout } from 'node:process';
import { parseArgs } from 'node:util';
import { createClient } from './client.js';
import { diffLines, formatDiff } from './diff.js';
import { isElgavioError } from './errors.js';
import { generateTypes } from './generate.js';
import { SDK_VERSION } from './version.js';

const DEFAULT_OUTPUT = 'elgavio-types.ts';
const CONFIG_FILE = 'elgavio.config.json';
const HASH_LINE = /^\/\/ elgavio-types-hash: ([0-9a-f]+)$/m;

const USAGE = `Usage: elgavio <command> [options]

Commands:
  types   Write the project's content types from its live schema.
  check   Fail when the committed types no longer match the live schema.

Options:
  --out <file>      Where the types file goes (default: ${DEFAULT_OUTPUT}, or "output" in ${CONFIG_FILE}).
  --api-url <url>   The API to read (default: ELGAVIO_API_URL, else https://api.elgavio.com).
  --token <token>   A delivery token. Prefer ELGAVIO_TOKEN: a flag stays in your shell history.
  -h, --help
  -v, --version

ELGAVIO_TOKEN and ELGAVIO_API_URL are read from the environment, then .env.local, then .env.`;

export class CliError extends Error {}

// The subset of dotenv every framework agrees on: `KEY=value`, `export`, quotes, `#` comments.
const parseDotenv = (text: string): Record<string, string> => {
  const values: Record<string, string> = {};
  for (const raw of text.split(/\r?\n/)) {
    const match = /^\s*(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)$/.exec(raw);
    if (match === null) {
      continue;
    }
    const [, key = '', rest = ''] = match;
    const quoted = /^(['"])(.*)\1\s*(?:#.*)?$/.exec(rest);
    values[key] = quoted === null ? rest.replace(/\s+#.*$/, '').trim() : (quoted[2] ?? '');
  }
  return values;
};

const readOptional = async (path: string) =>
  existsSync(path) ? await readFile(path, 'utf8') : null;

const loadSetting = async (name: string, dir: string): Promise<string | undefined> => {
  const fromEnv = env[name];
  if (fromEnv !== undefined && fromEnv !== '') {
    return fromEnv;
  }
  for (const file of ['.env.local', '.env']) {
    const text = await readOptional(resolve(dir, file));
    const value = text === null ? undefined : parseDotenv(text)[name];
    if (value !== undefined && value !== '') {
      return value;
    }
  }
  return undefined;
};

const loadOutput = async (dir: string, flag: string | undefined): Promise<string> => {
  if (flag !== undefined) {
    return resolve(dir, flag);
  }
  const text = await readOptional(resolve(dir, CONFIG_FILE));
  if (text === null) {
    return resolve(dir, DEFAULT_OUTPUT);
  }
  const config = JSON.parse(text) as unknown;
  const output =
    typeof config === 'object' && config !== null && 'output' in config ? config.output : undefined;
  if (output !== undefined && typeof output !== 'string') {
    throw new CliError(`${CONFIG_FILE}: "output" must be a path.`);
  }
  return resolve(dir, output ?? DEFAULT_OUTPUT);
};

const hashOf = (body: string) => createHash('sha256').update(body).digest('hex').slice(0, 16);

/** The file `elgavio types` writes: a header naming the body's hash, which `check` compares. */
export const typesFile = (body: string): string =>
  [
    `// Generated by \`elgavio types\` (@elgavio/sdk ${SDK_VERSION}) from the project's delivery schema.`,
    "// Don't edit it: `elgavio check` fails once it no longer matches. Rerun `elgavio types`.",
    `// elgavio-types-hash: ${hashOf(body)}`,
    '',
    body,
  ].join('\n');

const fetchBody = async (token: string | undefined, apiUrl: string | undefined) => {
  if (token === undefined) {
    throw new CliError(
      'No token: set ELGAVIO_TOKEN in the environment or in .env.local / .env (a delivery token, elg_…).',
    );
  }
  try {
    const schema = await createClient({ token, baseUrl: apiUrl, cache: false }).schema();
    return generateTypes(schema);
  } catch (error) {
    if (isElgavioError(error, 'DELIVERY_TOKEN_INVALID')) {
      throw new CliError('The token was refused: it is unknown, revoked or expired.');
    }
    if (isElgavioError(error)) {
      throw new CliError(`The API refused the schema: ${error.message}`);
    }
    throw new CliError(
      `Could not reach ${apiUrl ?? 'the API'}: ${error instanceof Error ? error.message : String(error)}`,
    );
  }
};

/** Runs one `elgavio` command line; the exit code it resolves to. */
export const run = async (args: string[], dir: string = cwd()): Promise<number> => {
  const { values, positionals } = parseArgs({
    args,
    allowPositionals: true,
    options: {
      out: { type: 'string' },
      'api-url': { type: 'string' },
      token: { type: 'string' },
      help: { type: 'boolean', short: 'h' },
      version: { type: 'boolean', short: 'v' },
    },
  });
  if (values.version === true) {
    stdout.write(`${SDK_VERSION}\n`);
    return 0;
  }
  const [command] = positionals;
  if (values.help === true || command === undefined) {
    stdout.write(`${USAGE}\n`);
    return command === undefined && values.help !== true ? 1 : 0;
  }
  if (command !== 'types' && command !== 'check') {
    throw new CliError(`Unknown command "${command}".\n\n${USAGE}`);
  }

  const output = await loadOutput(dir, values.out);
  const token = values.token ?? (await loadSetting('ELGAVIO_TOKEN', dir));
  const apiUrl = values['api-url'] ?? (await loadSetting('ELGAVIO_API_URL', dir));
  const body = await fetchBody(token, apiUrl);
  const file = typesFile(body);

  if (command === 'types') {
    await mkdir(dirname(output), { recursive: true });
    await writeFile(output, file);
    stdout.write(`Wrote ${output}\n`);
    return 0;
  }

  const committed = await readOptional(output);
  if (committed === null) {
    stderr.write(`${output} doesn't exist. Run \`elgavio types\` and commit it.\n`);
    return 1;
  }
  // The hash, not the text: a formatter may rewrite the file without changing what it says.
  if (HASH_LINE.exec(committed)?.[1] === hashOf(body)) {
    stdout.write(`${output} matches the schema.\n`);
    return 0;
  }
  stderr.write(
    `${output} no longer matches the project's schema. Run \`elgavio types\` and commit the result.\n\n` +
      `${formatDiff(diffLines(committed.split('\n'), file.split('\n')))}\n`,
  );
  return 1;
};
