import { mkdtemp, readFile, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { run } from './command.js';
import type { DeliverySchema } from './types.js';

const schema = (fieldKey: string): DeliverySchema => ({
  locales: [{ code: 'en', default: true }],
  collections: [
    {
      key: 'posts',
      name: 'Posts',
      pathPrefix: null,
      hierarchical: false,
      single: false,
      fields: [
        {
          key: fieldKey,
          label: 'Excerpt',
          helpText: null,
          cardinality: { kind: 'one' },
          required: false,
          type: 'text',
          config: { maxLength: null },
        },
      ],
      filters: [],
      sort: ['title'],
    },
  ],
  blocks: [],
});

let dir: string;
let out: string[];
let err: string[];
let served: DeliverySchema;
let sent: { url: string; authorization: string | undefined }[];

beforeEach(async () => {
  dir = await mkdtemp(join(tmpdir(), 'elgavio-cli-'));
  out = [];
  err = [];
  served = schema('excerpt');
  sent = [];
  vi.stubEnv('ELGAVIO_TOKEN', '');
  vi.stubEnv('ELGAVIO_API_URL', '');
  vi.spyOn(process.stdout, 'write').mockImplementation((chunk) => {
    out.push(String(chunk));
    return true;
  });
  vi.spyOn(process.stderr, 'write').mockImplementation((chunk) => {
    err.push(String(chunk));
    return true;
  });
  vi.stubGlobal(
    'fetch',
    vi.fn((url: string, init: RequestInit) => {
      sent.push({
        url,
        authorization: (init.headers as Record<string, string>).Authorization,
      });
      return Promise.resolve(Response.json(served));
    }),
  );
});

afterEach(() => {
  vi.unstubAllEnvs();
  vi.unstubAllGlobals();
  vi.restoreAllMocks();
});

describe('elgavio types', () => {
  it('reads the token and API from .env.local over .env, and writes the default file', async () => {
    await writeFile(join(dir, '.env'), 'ELGAVIO_TOKEN=elg_env\nELGAVIO_API_URL=https://api.test\n');
    await writeFile(join(dir, '.env.local'), 'export ELGAVIO_TOKEN="elg_local" # mine\n');
    expect(await run(['types'], dir)).toBe(0);
    expect(sent).toEqual([
      { url: 'https://api.test/delivery/v1/schema', authorization: 'Bearer elg_local' },
    ]);
    const file = await readFile(join(dir, 'elgavio-types.ts'), 'utf8');
    expect(file).toMatch(/^\/\/ Generated by `elgavio types`/);
    expect(file).toContain('excerpt?: string;');
  });

  it('prefers the environment, and the flags over both', async () => {
    vi.stubEnv('ELGAVIO_TOKEN', 'elg_shell');
    await writeFile(join(dir, '.env'), 'ELGAVIO_TOKEN=elg_file\n');
    await run(['types'], dir);
    await run(['types', '--token', 'elg_flag', '--api-url', 'https://flag.test'], dir);
    expect(sent).toEqual([
      { url: 'https://api.elgavio.com/delivery/v1/schema', authorization: 'Bearer elg_shell' },
      { url: 'https://flag.test/delivery/v1/schema', authorization: 'Bearer elg_flag' },
    ]);
  });

  it('writes where elgavio.config.json says, unless --out does', async () => {
    vi.stubEnv('ELGAVIO_TOKEN', 'elg_x');
    await writeFile(join(dir, 'elgavio.config.json'), '{ "output": "src/content/types.ts" }');
    await run(['types'], dir);
    await expect(readFile(join(dir, 'src/content/types.ts'), 'utf8')).resolves.toContain(
      'ElgavioContent',
    );
    await run(['types', '--out', 'other.ts'], dir);
    await expect(readFile(join(dir, 'other.ts'), 'utf8')).resolves.toContain('ElgavioContent');
  });

  it('explains a missing token', async () => {
    await expect(run(['types'], dir)).rejects.toThrow('No token');
  });
});

describe('elgavio check', () => {
  beforeEach(() => {
    vi.stubEnv('ELGAVIO_TOKEN', 'elg_x');
  });

  it('passes while the schema is unchanged, however the file was reformatted', async () => {
    await run(['types'], dir);
    const path = join(dir, 'elgavio-types.ts');
    await writeFile(path, (await readFile(path, 'utf8')).replaceAll("'", '"'));
    expect(await run(['check'], dir)).toBe(0);
  });

  it('fails with a diff once a field is renamed', async () => {
    await run(['types'], dir);
    served = schema('summary');
    expect(await run(['check'], dir)).toBe(1);
    const message = err.join('');
    expect(message).toContain('no longer matches');
    expect(message).toContain('-   excerpt?: string;');
    expect(message).toContain('+   summary?: string;');
  });

  it('fails when the file was never written', async () => {
    expect(await run(['check'], dir)).toBe(1);
    expect(err.join('')).toContain("doesn't exist");
  });
});

describe('the command line', () => {
  it('prints the usage for no command, and refuses an unknown one', async () => {
    expect(await run([], dir)).toBe(1);
    expect(out.join('')).toContain('Usage: elgavio');
    await expect(run(['typo'], dir)).rejects.toThrow('Unknown command "typo"');
  });
});
