/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/delivery/v1/project": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The token's project: its languages, the default marked, and its collections. A `single` collection holds one entry, read through `/collections/{key}/entry`. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            locales: {
                                code: string;
                                default: boolean;
                            }[];
                            collections: {
                                key: string;
                                name: string;
                                pathPrefix: string | null;
                                hierarchical: boolean;
                                single: boolean;
                            }[];
                        };
                    };
                };
                /** @description An error, in the envelope every error shares. */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DeliveryErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/delivery/v1/schema": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The project's content types, for generating an app's types: each collection's fields and what it filters and sorts by, and each block. Fields nest through `group`; a `reference` names its target collections by key. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            locales: {
                                code: string;
                                default: boolean;
                            }[];
                            collections: {
                                key: string;
                                name: string;
                                pathPrefix: string | null;
                                hierarchical: boolean;
                                single: boolean;
                                /** @description The entry's own fields, by key. */
                                fields: components["schemas"]["DeliverySchemaField"][];
                                /** @description What `filter[<key>][<operator>]` takes in this collection. */
                                filters: {
                                    key: string;
                                    operators: ("eq" | "ne" | "in" | "lt" | "lte" | "gt" | "gte" | "contains" | "exists")[];
                                }[];
                                /** @description The keys `sort` takes in this collection. */
                                sort: string[];
                            }[];
                            blocks: {
                                /** @description The instance's `_block`. */
                                key: string;
                                name: string;
                                description: string | null;
                                /** @description The collection keys whose entries may hold it. */
                                availableIn: "all" | string[];
                                fields: components["schemas"]["DeliverySchemaField"][];
                            }[];
                        };
                    };
                };
                /** @description An error, in the envelope every error shares. */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DeliveryErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/delivery/v1/entries/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description One entry as published in the language asked for; 404 where it isn't. */
        get: {
            parameters: {
                query?: {
                    /** @description A language of the project's; its default language when left out. */
                    locale?: string;
                    /** @description Every rich-text value as an HTML string, the JSON document (images carry their `url`), or plain text with a blank line between blocks. */
                    richText?: "html" | "json" | "text";
                    /** @description Draft mode: each entry as its draft where that draft would pass publish validation, else as published; an entry never published shows once its draft would pass. Needs a token with the `preview` scope, or a preview session in `Elgavio-Preview`. Never cached. */
                    draft?: "true" | "false";
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DeliveredEntry"];
                    };
                };
                /** @description An error, in the envelope every error shares. */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DeliveryErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/delivery/v1/collections/{key}/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description A collection's published entries, a page at a time. Unsorted and unfiltered, a hierarchical collection lists in tree order, depth-first, any other newest published first; sorted or filtered, every collection lists flat.
         *
         *     `filter[<key>]=<value>` keeps the entries whose field equals the value, and `filter[<key>][<operator>]=<value>` applies another operator; several filters must all match. A key is `publishedAt` or a field marked filterable. Operators: `eq`, `ne` (entries without a value too), `in` (a comma list), `lt`, `lte`, `gt` and `gte` on numbers and dates, `contains` on a field holding several values, and `exists` (`true` or `false`). A reference compares its target entry ids. Dates are `2026-10-03` or a full ISO time.
         */
        get: {
            parameters: {
                query?: {
                    /** @description A language of the project's; its default language when left out. */
                    locale?: string;
                    /** @description Every rich-text value as an HTML string, the JSON document (images carry their `url`), or plain text with a blank line between blocks. */
                    richText?: "html" | "json" | "text";
                    page?: number;
                    limit?: number;
                    /** @description A comma list of the top-level keys to serve, `blocks` among them; the system keys always come. */
                    fields?: string;
                    /** @description A comma list of keys, each descending with a leading `-`: `-publishDate,title`. Sorts by `title`, `publishedAt`, or a filterable field holding one text, number, date, boolean or list value. Text compares in the language asked for. Entries without a value come last. */
                    sort?: string;
                    /** @description Draft mode: each entry as its draft where that draft would pass publish validation, else as published; an entry never published shows once its draft would pass. Needs a token with the `preview` scope, or a preview session in `Elgavio-Preview`. Never cached. */
                    draft?: "true" | "false";
                };
                header?: never;
                path: {
                    key: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["DeliveredEntry"][];
                            meta: {
                                page: number;
                                limit: number;
                                total: number;
                                totalPages: number;
                            };
                        };
                    };
                };
                /** @description An error, in the envelope every error shares. */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DeliveryErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/delivery/v1/collections/{key}/entry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description A `single` collection's one entry; 404 while it isn't published. Any other collection is `DELIVERY_NOT_SINGLE`. */
        get: {
            parameters: {
                query?: {
                    /** @description A language of the project's; its default language when left out. */
                    locale?: string;
                    /** @description Every rich-text value as an HTML string, the JSON document (images carry their `url`), or plain text with a blank line between blocks. */
                    richText?: "html" | "json" | "text";
                    /** @description Draft mode: each entry as its draft where that draft would pass publish validation, else as published; an entry never published shows once its draft would pass. Needs a token with the `preview` scope, or a preview session in `Elgavio-Preview`. Never cached. */
                    draft?: "true" | "false";
                };
                header?: never;
                path: {
                    key: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DeliveredEntry"];
                    };
                };
                /** @description An error, in the envelope every error shares. */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DeliveryErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/delivery/v1/collections/{key}/tree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description A hierarchical collection's published entries, nested, without their content: for menus. Not paged. Any other collection is `DELIVERY_NOT_HIERARCHICAL`. */
        get: {
            parameters: {
                query?: {
                    /** @description A language of the project's; its default language when left out. */
                    locale?: string;
                    /** @description Draft mode: each entry as its draft where that draft would pass publish validation, else as published; an entry never published shows once its draft would pass. Needs a token with the `preview` scope, or a preview session in `Elgavio-Preview`. Never cached. */
                    draft?: "true" | "false";
                };
                header?: never;
                path: {
                    key: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["DeliveredTreeNode"][];
                        };
                    };
                };
                /** @description An error, in the envelope every error shares. */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DeliveryErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/delivery/v1/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description What a public path is in the language: the entry published there, else the redirect from it; 404 for neither. An entry always wins over a redirect. */
        get: {
            parameters: {
                query: {
                    /** @description A language of the project's; its default language when left out. */
                    locale?: string;
                    /** @description Every rich-text value as an HTML string, the JSON document (images carry their `url`), or plain text with a blank line between blocks. */
                    richText?: "html" | "json" | "text";
                    /** @description A public path, as an entry's `path` reads: `/blog/hello`. A trailing slash is ignored. */
                    path: string;
                    /** @description Draft mode: each entry as its draft where that draft would pass publish validation, else as published; an entry never published shows once its draft would pass. Needs a token with the `preview` scope, or a preview session in `Elgavio-Preview`. Never cached. */
                    draft?: "true" | "false";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            type: "entry";
                            /** @description The entry's collection key. */
                            collection: string;
                            entry: components["schemas"]["DeliveredEntry"];
                        } | {
                            /** @enum {string} */
                            type: "redirect";
                            /** @description A public path, leading slash included. */
                            to: string;
                            /** @description 301 when true, else 302. */
                            permanent: boolean;
                        };
                    };
                };
                /** @description An error, in the envelope every error shares. */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DeliveryErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/delivery/v1/paths": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Every entry published in the language, with its other languages, for static generation and sitemaps: by collection, then path. */
        get: {
            parameters: {
                query?: {
                    /** @description A language of the project's; its default language when left out. */
                    locale?: string;
                    page?: number;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                id: string;
                                collection: string;
                                locale: string;
                                path: string;
                                publishedAt: string;
                                /** @description Every other language the entry is delivered in. */
                                alternates: {
                                    locale: string;
                                    path: string;
                                }[];
                            }[];
                            meta: {
                                page: number;
                                limit: number;
                                total: number;
                                totalPages: number;
                            };
                        };
                    };
                };
                /** @description An error, in the envelope every error shares. */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DeliveryErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/delivery/v1/redirects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The project's redirects in the language, by `from`. Each leads straight to its final target: chains never reach here. */
        get: {
            parameters: {
                query?: {
                    /** @description A language of the project's; its default language when left out. */
                    locale?: string;
                    page?: number;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                /** @description A public path, leading slash included. */
                                from: string;
                                /** @description A public path, leading slash included. */
                                to: string;
                                /** @description 301 when true, else 302. */
                                permanent: boolean;
                            }[];
                            meta: {
                                page: number;
                                limit: number;
                                total: number;
                                totalPages: number;
                            };
                        };
                    };
                };
                /** @description An error, in the envelope every error shares. */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DeliveryErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/delivery/v1/changes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description What changed since `since`, oldest first, for an app keeping content on the device: ids and kinds, never content, so refetch what you hold. Up to 1000 at a time; changes are kept 90 days, and an older `since` answers `resync`. */
        get: {
            parameters: {
                query?: {
                    /** @description The `next` of the last answer. Left out, the answer is only `next` and `resync`: take it before fetching everything, and nothing changed in between is missed. */
                    since?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                /** @description Several changes of one write share it. */
                                seq: number;
                                at: string;
                                /**
                                 * @description `published`: an entry served for the first time or served differently, refetch it. `unpublished` and `deleted`: no longer served. `moved`: a new path or place in its tree. `media`: a media record's alt text, for every entry showing it. `redirect`: the redirect from `path` is new, changed or gone. `schema`: collections, blocks or languages changed, refetch what depends on them.
                                 * @enum {string}
                                 */
                                kind: "published" | "unpublished" | "deleted" | "moved" | "media" | "redirect" | "schema";
                                /** @description The entry's id, or the media record's for `media`; an entry's other languages and entries referencing it read it too. */
                                id: string | null;
                                /** @description The entry's collection key; for `schema`, the collection changed, null for others. */
                                collection: string | null;
                                locale: string | null;
                                /** @description A public path: an entry's (the one it had, once gone), or a redirect's `from`. */
                                path: string | null;
                                /** @description For `moved`, the path it had. */
                                previousPath: string | null;
                            }[];
                            /** @description The `since` to ask with next time. */
                            next: number;
                            /** @description More changes are waiting: ask again with `next` now. */
                            hasMore: boolean;
                            /** @description The changes since then are no longer kept, or `since` was left out: refetch everything, then continue from `next`. */
                            resync: boolean;
                        };
                    };
                };
                /** @description An error, in the envelope every error shares. */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DeliveryErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/delivery/v1/preview/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Checks a preview code from the entry editor's Preview button, valid five minutes, and answers the entry to open in draft mode, with a preview session for reading drafts. A code of another project is `DELIVERY_PREVIEW_CODE_INVALID`, as an expired one is. */
        get: {
            parameters: {
                query: {
                    /** @description The `elgavioPreview` parameter the preview URL was opened with. */
                    code: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            entry: {
                                id: string;
                                collection: string;
                                locale: string;
                                path: string;
                            };
                            /** @description Sent as `Elgavio-Preview` with `draft=true`, it lets this token read the project's drafts for an hour: how a public token, which never reads them on its own, previews. */
                            previewSession: {
                                value: string;
                                expiresAt: string;
                            };
                        };
                    };
                };
                /** @description An error, in the envelope every error shares. */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DeliveryErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        DeliveryErrorResponse: {
            error: {
                /** @enum {string} */
                code: "BAD_REQUEST" | "VALIDATION_ERROR" | "UNAUTHORIZED" | "FORBIDDEN" | "NOT_FOUND" | "RATE_LIMITED" | "INTERNAL_SERVER_ERROR";
                /** @enum {string|null} */
                reason: "FIELD_ERRORS" | "DELIVERY_TOKEN_INVALID" | "DELIVERY_SCOPE_MISSING" | "DELIVERY_LOCALE_UNKNOWN" | "DELIVERY_NOT_SINGLE" | "DELIVERY_NOT_HIERARCHICAL" | "DELIVERY_PREVIEW_CODE_INVALID" | null;
                message: string;
                fieldErrors: {
                    field: string;
                    /** @enum {string} */
                    code: "TOO_SHORT" | "TOO_LONG" | "TOO_FEW" | "TOO_MANY" | "TOO_SMALL" | "TOO_LARGE" | "INVALID_TYPE" | "INVALID_FORMAT" | "INVALID_VALUE" | "UNKNOWN_FIELD" | "INVALID" | "DELIVERY_FIELDS_UNKNOWN" | "DELIVERY_FILTER_SYNTAX" | "DELIVERY_FILTER_UNKNOWN_FIELD" | "DELIVERY_FILTER_NOT_FILTERABLE" | "DELIVERY_FILTER_OPERATOR" | "DELIVERY_FILTER_VALUE" | "DELIVERY_SORT_UNKNOWN_FIELD" | "DELIVERY_SORT_NOT_SORTABLE";
                    message: string;
                    params?: {
                        [key: string]: number | string | boolean | string[];
                    };
                }[];
                /** @enum {string|null} */
                reasonData: null;
            };
        };
        /** @description A `media` value. */
        DeliveredMedia: {
            id: string;
            /** @description Absolute, ending in the canonical extension. */
            url: string;
            alt: string;
            mimeType: string;
            byteSize: number;
            width: number | null;
            height: number | null;
        };
        /** @description A `list` value: the option chosen. */
        DeliveredListOption: {
            value: string;
            label: string;
        };
        /** @description A `reference` value: its target, with the field's preview fields by key beside these. */
        DeliveredReference: {
            id: string;
            /** @description The target's collection key. */
            collection: string;
            path: string;
            title: string;
        } & {
            [key: string]: unknown;
        };
        /** @description A `link` value. */
        DeliveredLink: {
            /** @enum {string} */
            kind: "external";
            url: string | null;
        } | {
            /** @enum {string} */
            kind: "anchor";
            anchor: string | null;
        } | {
            /** @enum {string} */
            kind: "entry";
            /** @description The target's public path. */
            url: string;
            entry: {
                id: string;
                collection: string;
                path: string;
                title: string;
            };
        };
        /** @description One of `blocks`: the block's fields by key beside these. */
        DeliveredBlockInstance: {
            /** @description Stable across saves: usable as a key. */
            _id: string;
            /** @description The block's key. */
            _block: string;
        } & {
            [key: string]: unknown;
        };
        DeliveredRichTextText: {
            /** @enum {string} */
            type: "text";
            text: string;
            marks?: ({
                /** @enum {string} */
                type: "bold" | "italic" | "underline" | "strike" | "code" | "highlight" | "subscript" | "superscript";
            } | {
                /** @enum {string} */
                type: "link";
                attrs: {
                    href: string;
                };
            })[];
        };
        DeliveredRichTextNode: {
            /** @enum {string} */
            type: "paragraph";
            content?: (components["schemas"]["DeliveredRichTextText"] | {
                /** @enum {string} */
                type: "hardBreak";
            })[];
        } | {
            /** @enum {string} */
            type: "heading";
            attrs: {
                level: number;
            };
            content?: (components["schemas"]["DeliveredRichTextText"] | {
                /** @enum {string} */
                type: "hardBreak";
            })[];
        } | {
            /** @enum {string} */
            type: "codeBlock";
            content?: {
                /** @enum {string} */
                type: "text";
                text: string;
            }[];
        } | {
            /** @enum {string} */
            type: "horizontalRule";
        } | {
            /** @enum {string} */
            type: "image";
            attrs: {
                mediaId: string;
                url: string;
                alt: string;
                width: number | null;
                height: number | null;
                mimeType: string;
            };
        } | {
            /** @enum {string} */
            type: "blockquote";
            content: components["schemas"]["DeliveredRichTextNode"][];
        } | {
            /** @enum {string} */
            type: "bulletList";
            content: components["schemas"]["DeliveredRichTextNode"][];
        } | {
            /** @enum {string} */
            type: "orderedList";
            attrs?: {
                start: number;
            };
            content: components["schemas"]["DeliveredRichTextNode"][];
        } | {
            /** @enum {string} */
            type: "listItem";
            content: components["schemas"]["DeliveredRichTextNode"][];
        };
        /** @description A `richText` value with `?richText=json`. With `html` or `text` it's a string. */
        DeliveredRichTextDocument: {
            /** @enum {string} */
            type: "doc";
            content: components["schemas"]["DeliveredRichTextNode"][];
        };
        /** @description The collection's fields by key, flat beside these, and the block stack as `blocks`. */
        DeliveredEntry: {
            id: string;
            /** @description The collection's key. */
            collection: string;
            locale: string;
            title: string;
            slug: string;
            /** @description The public path, prefix included, from the root: `/blog/hello`. */
            path: string;
            publishedAt: string;
            /** @description Every other language the entry is delivered in. */
            alternates: {
                locale: string;
                path: string;
            }[];
        } & {
            [key: string]: unknown;
        };
        DeliveredTreeNode: {
            id: string;
            title: string;
            slug: string;
            path: string;
            children: components["schemas"]["DeliveredTreeNode"][];
        };
        /** @description The body of a webhook's `POST`. `Elgavio-Signature` is `t=<unix seconds>,v1=<hex>`, the HMAC-SHA256 of `<t>.<body>` under the signing secret. */
        DeliveryWebhookPayload: {
            /** @enum {string} */
            event: "content.changed";
            /**
             * @description `publish`: a minute after the last change. `deploy`: someone pressed the project's Deploy button.
             * @enum {string}
             */
            trigger: "publish" | "deploy";
            project: {
                id: string;
            };
            /** @description The changes are those after this `seq`. */
            since: number;
            /** @description The `seq` they reach, a `since` for `/changes`. */
            next: number;
            /** @description In order, at most 100. */
            changes: {
                /** @description Several changes of one write share it. */
                seq: number;
                at: string;
                /**
                 * @description `published`: an entry served for the first time or served differently, refetch it. `unpublished` and `deleted`: no longer served. `moved`: a new path or place in its tree. `media`: a media record's alt text, for every entry showing it. `redirect`: the redirect from `path` is new, changed or gone. `schema`: collections, blocks or languages changed, refetch what depends on them.
                 * @enum {string}
                 */
                kind: "published" | "unpublished" | "deleted" | "moved" | "media" | "redirect" | "schema";
                /** @description The entry's id, or the media record's for `media`; an entry's other languages and entries referencing it read it too. */
                id: string | null;
                /** @description The entry's collection key; for `schema`, the collection changed, null for others. */
                collection: string | null;
                locale: string | null;
                /** @description A public path: an entry's (the one it had, once gone), or a redirect's `from`. */
                path: string | null;
                /** @description For `moved`, the path it had. */
                previousPath: string | null;
            }[];
            /** @description More changes than `changes` holds: read them all from `/changes?since=`. */
            truncated: boolean;
        };
        DeliverySchemaField: {
            /** @description The key it is served under. */
            key: string;
            label: string;
            helpText: string | null;
            /** @description `many` is served as an array, always present, `[]` when empty. */
            cardinality: {
                /** @enum {string} */
                kind: "one";
            } | {
                /** @enum {string} */
                kind: "many";
                min: number | null;
                max: number | null;
            };
            /** @description Only on `one`: always present and never empty. An optional field is left out when empty; a `group` is always present. */
            required: boolean;
            /** @enum {string} */
            type: "text";
            config: {
                maxLength: number | null;
            };
        } | {
            /** @description The key it is served under. */
            key: string;
            label: string;
            helpText: string | null;
            /** @description `many` is served as an array, always present, `[]` when empty. */
            cardinality: {
                /** @enum {string} */
                kind: "one";
            } | {
                /** @enum {string} */
                kind: "many";
                min: number | null;
                max: number | null;
            };
            /** @description Only on `one`: always present and never empty. An optional field is left out when empty; a `group` is always present. */
            required: boolean;
            /** @enum {string} */
            type: "richText";
        } | {
            /** @description The key it is served under. */
            key: string;
            label: string;
            helpText: string | null;
            /** @description `many` is served as an array, always present, `[]` when empty. */
            cardinality: {
                /** @enum {string} */
                kind: "one";
            } | {
                /** @enum {string} */
                kind: "many";
                min: number | null;
                max: number | null;
            };
            /** @description Only on `one`: always present and never empty. An optional field is left out when empty; a `group` is always present. */
            required: boolean;
            /** @enum {string} */
            type: "number";
            config: {
                min: number | null;
                max: number | null;
                integer: boolean;
            };
        } | {
            /** @description The key it is served under. */
            key: string;
            label: string;
            helpText: string | null;
            /** @description `many` is served as an array, always present, `[]` when empty. */
            cardinality: {
                /** @enum {string} */
                kind: "one";
            } | {
                /** @enum {string} */
                kind: "many";
                min: number | null;
                max: number | null;
            };
            /** @description Only on `one`: always present and never empty. An optional field is left out when empty; a `group` is always present. */
            required: boolean;
            /** @enum {string} */
            type: "boolean";
        } | {
            /** @description The key it is served under. */
            key: string;
            label: string;
            helpText: string | null;
            /** @description `many` is served as an array, always present, `[]` when empty. */
            cardinality: {
                /** @enum {string} */
                kind: "one";
            } | {
                /** @enum {string} */
                kind: "many";
                min: number | null;
                max: number | null;
            };
            /** @description Only on `one`: always present and never empty. An optional field is left out when empty; a `group` is always present. */
            required: boolean;
            /** @enum {string} */
            type: "date";
            config: {
                /** @description A full ISO time when true, else a day: `2026-10-03`. */
                time: boolean;
            };
        } | {
            /** @description The key it is served under. */
            key: string;
            label: string;
            helpText: string | null;
            /** @description `many` is served as an array, always present, `[]` when empty. */
            cardinality: {
                /** @enum {string} */
                kind: "one";
            } | {
                /** @enum {string} */
                kind: "many";
                min: number | null;
                max: number | null;
            };
            /** @description Only on `one`: always present and never empty. An optional field is left out when empty; a `group` is always present. */
            required: boolean;
            /** @enum {string} */
            type: "list";
            config: {
                options: {
                    value: string;
                    label: string;
                }[];
            };
        } | {
            /** @description The key it is served under. */
            key: string;
            label: string;
            helpText: string | null;
            /** @description `many` is served as an array, always present, `[]` when empty. */
            cardinality: {
                /** @enum {string} */
                kind: "one";
            } | {
                /** @enum {string} */
                kind: "many";
                min: number | null;
                max: number | null;
            };
            /** @description Only on `one`: always present and never empty. An optional field is left out when empty; a `group` is always present. */
            required: boolean;
            /** @enum {string} */
            type: "json";
        } | {
            /** @description The key it is served under. */
            key: string;
            label: string;
            helpText: string | null;
            /** @description `many` is served as an array, always present, `[]` when empty. */
            cardinality: {
                /** @enum {string} */
                kind: "one";
            } | {
                /** @enum {string} */
                kind: "many";
                min: number | null;
                max: number | null;
            };
            /** @description Only on `one`: always present and never empty. An optional field is left out when empty; a `group` is always present. */
            required: boolean;
            /** @enum {string} */
            type: "media";
            config: {
                accept: string | null;
            };
        } | {
            /** @description The key it is served under. */
            key: string;
            label: string;
            helpText: string | null;
            /** @description `many` is served as an array, always present, `[]` when empty. */
            cardinality: {
                /** @enum {string} */
                kind: "one";
            } | {
                /** @enum {string} */
                kind: "many";
                min: number | null;
                max: number | null;
            };
            /** @description Only on `one`: always present and never empty. An optional field is left out when empty; a `group` is always present. */
            required: boolean;
            /** @enum {string} */
            type: "reference";
            config: {
                /** @description The collections it may point into. */
                targets: {
                    /** @description A collection's key. */
                    collection: string;
                    /** @description That collection's field keys served beside the target's title. */
                    previewFields: string[];
                }[];
            };
        } | {
            /** @description The key it is served under. */
            key: string;
            label: string;
            helpText: string | null;
            /** @description `many` is served as an array, always present, `[]` when empty. */
            cardinality: {
                /** @enum {string} */
                kind: "one";
            } | {
                /** @enum {string} */
                kind: "many";
                min: number | null;
                max: number | null;
            };
            /** @description Only on `one`: always present and never empty. An optional field is left out when empty; a `group` is always present. */
            required: boolean;
            /** @enum {string} */
            type: "link";
        } | {
            /** @description The key it is served under. */
            key: string;
            label: string;
            helpText: string | null;
            /** @description `many` is served as an array, always present, `[]` when empty. */
            cardinality: {
                /** @enum {string} */
                kind: "one";
            } | {
                /** @enum {string} */
                kind: "many";
                min: number | null;
                max: number | null;
            };
            /** @description Only on `one`: always present and never empty. An optional field is left out when empty; a `group` is always present. */
            required: boolean;
            /** @enum {string} */
            type: "group";
            children: components["schemas"]["DeliverySchemaField"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
